# 権限の設定(sudo権限)
sudo: required

# Dockerを使う
service: docker

# コンテナを起動＆HerokuのDocker Registryにログイン
before_install:
  - docker-compose up --build -d
  - docker login -u "$HEROKU_USERNAME" -p "$HEORKU_API_KEY" registry.heroku.com

# DB準備〜テストを実行
script:
  - docker-compose exec --env "RAILS_ENV=test" web rails db:create
  - docker-compose exec --env "RAILS_ENV=test" web rails db:migrate
  - docker-compose exec --env "RAILS_ENV=test" web rails test

# デプロイ
deploy:
  provider: script
  # scriptが複数になる場合は;で区切る
  script:
    docker build -t registry.heroku.com/$HEROKU_APP_NAME/web -f Dockerfile.prod .;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku run --app $HEROKU_APP_NAME rails db:migrate;
  # デプロイはmasterにmergeされた時だけデプロイする
  on:
    branch: master 
